# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('userprofileplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserProfile.UserProfilePlugin')),
                ('activated', models.BooleanField(default=False)),
                ('activationKey', models.CharField(default=b'', max_length=6, unique=True)),
                ('chatId', models.CharField(default=b'', max_length=32, unique=True)),
                ('usingTelegramAlerts', models.BooleanField(default=False)),
            ],
            bases=('UserProfile.userprofileplugin',),
        ),
    ]
