# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20180220_1727'),
        ('TelegramUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('activationKey', models.CharField(default=b'', max_length=6, unique=True)),
                ('chatId', models.CharField(default=b'', max_length=32, unique=True)),
                ('usingTelegramAlerts', models.BooleanField(default=False)),
                ('userProfile', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegramuser', to='UserProfile.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='userprofileplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
