# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramUser', '0002_auto_20180220_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUserProfile',
            new_name='TelegramUser',
        ),
    ]
