# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2026-04-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramUser', '0004_auto_20180305_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='activationKey',
            field=models.CharField(default=b'', max_length=32, unique=True),
        ),
    ]
