# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2026-04-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramUser', '0005_auto_20260419_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='activationKeyHash',
            field=models.CharField(db_index=True, default=b'', max_length=64),
        ),
    ]
