# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 21:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guinness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('approved', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=40)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=12)),
                ('mapLink', models.TextField(default=b'')),
                ('closed', models.BooleanField(default=False)),
                ('servingGuinness', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsSingleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubsInDb', models.IntegerField(default=0)),
                ('cheapestPub', models.TextField(default=b'')),
                ('dearestPub', models.TextField(default=b'')),
                ('averagePrice', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6)),
                ('standardDevation', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('percentageVisited', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('closedPubs', models.IntegerField(default=0)),
                ('notServingGuinness', models.IntegerField(default=0)),
                ('lastCalculated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContributionsSingleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastCalculated', models.DateTimeField(auto_now=True)),
                ('mostFirstVerified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_first_verifications', to='UserProfile.UserProfile')),
                ('mostLastVerified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_last_verifications', to='UserProfile.UserProfile')),
                ('mostVisited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_visited', to='UserProfile.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='guinness',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.CreateModel(
            name='GuindexUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubsVisited', models.IntegerField(default=0)),
                ('originalPrices', models.IntegerField(default=0)),
                ('currentVerifications', models.IntegerField(default=0)),
                ('lastCalculated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
