# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuindexUser',
            fields=[
                ('userprofileplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserProfile.UserProfilePlugin')),
                ('pubsVisited', models.IntegerField(default=True)),
                ('originalPrices', models.IntegerField(default=True)),
                ('currentVerifications', models.IntegerField(default=True)),
            ],
            bases=('UserProfile.userprofileplugin',),
        ),
        migrations.CreateModel(
            name='Guinness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=b'', max_length=40, unique=True)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=12)),
                ('mapLink', models.TextField(default=b'')),
                ('closed', models.BooleanField(default=False)),
                ('servingGuinness', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descripton', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='guinness',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
    ]
