# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guindex', '0001_initial'),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='guinness',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='guinness',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
    ]
