# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0002_auto_20171226_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
