# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0003_auto_20171214_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pub',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pub',
            name='mapLink',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(default=b'', max_length=40, unique=True),
        ),
    ]
