# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180112_2059'),
        ('Guindex', '0003_auto_20180114_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='approved',
            new_name='pendingApproval',
        ),
        migrations.AddField(
            model_name='pub',
            name='pendingApprovalContributor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendingAdder', to='UserProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='pub',
            name='pendingApprovalTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
