# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0003_auto_20171226_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guindexuser',
            name='userprofileplugin_ptr',
        ),
        migrations.AlterField(
            model_name='guinness',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='GuindexUser',
        ),
    ]
