# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20171214_2035'),
        ('Guindex', '0004_auto_20171220_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuindexUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAlerts', models.BooleanField(default=False)),
                ('telegramAlerts', models.BooleanField(default=False)),
                ('pubsVisited', models.IntegerField(default=True)),
                ('originalPrices', models.IntegerField(default=True)),
                ('currentVerifications', models.IntegerField(default=True)),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='pub',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pub',
            name='servingGuinness',
            field=models.BooleanField(default=True),
        ),
    ]
