# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0004_auto_20180115_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='pendingApproval',
            field=models.BooleanField(default=False),
        ),
    ]
