# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_userprofile_guindexuser'),
        ('Guindex', '0006_alertssingleton'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContributionsSingleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostFirstVerified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_first_verifications', to='UserProfile.UserProfile')),
                ('mostLastVerified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_last_verifications', to='UserProfile.UserProfile')),
                ('mostVisited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_visited', to='UserProfile.UserProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserContribution',
        ),
    ]
