# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0006_auto_20180115_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='guinness',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pub',
            name='pendingApprovalRejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pub',
            name='pendingClosedRejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pub',
            name='pendingNotServingGuinnessRejected',
            field=models.BooleanField(default=False),
        ),
    ]
