# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0007_auto_20171228_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontributionssingleton',
            name='mostFirstVerified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_first_verifications', to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usercontributionssingleton',
            name='mostLastVerified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_last_verifications', to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usercontributionssingleton',
            name='mostVisited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_visited', to='UserProfile.UserProfile'),
        ),
    ]
