# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0008_auto_20180117_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='pendingClosedRejected',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingNotServingGuinnessRejected',
        ),
    ]
