# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0008_auto_20171228_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontributionssingleton',
            name='lastCalculated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
