# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0009_auto_20180117_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='cheapestPub',
        ),
        migrations.AddField(
            model_name='statisticssingleton',
            name='cheapestPub',
            field=models.ManyToManyField(related_name='cheapest_pub', to='Guindex.Pub'),
        ),
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='dearestPub',
        ),
        migrations.AddField(
            model_name='statisticssingleton',
            name='dearestPub',
            field=models.ManyToManyField(related_name='dearest_pub', to='Guindex.Pub'),
        ),
    ]
