# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0010_auto_20180129_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='cheapestPub',
        ),
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='dearestPub',
        ),
        migrations.AddField(
            model_name='statisticssingleton',
            name='cheapestPubs',
            field=models.ManyToManyField(related_name='cheapest_pubs', to='Guindex.Pub'),
        ),
        migrations.AddField(
            model_name='statisticssingleton',
            name='dearestPubs',
            field=models.ManyToManyField(related_name='dearest_pubs', to='Guindex.Pub'),
        ),
    ]
