# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180112_2059'),
        ('Guindex', '0011_auto_20180129_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontributionssingleton',
            name='mostFirstVerified',
        ),
        migrations.AddField(
            model_name='usercontributionssingleton',
            name='mostFirstVerified',
            field=models.ManyToManyField(related_name='most_first_verifications', to='UserProfile.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='usercontributionssingleton',
            name='mostLastVerified',
        ),
        migrations.AddField(
            model_name='usercontributionssingleton',
            name='mostLastVerified',
            field=models.ManyToManyField(related_name='most_last_verifications', to='UserProfile.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='usercontributionssingleton',
            name='mostVisited',
        ),
        migrations.AddField(
            model_name='usercontributionssingleton',
            name='mostVisited',
            field=models.ManyToManyField(related_name='most_visited', to='UserProfile.UserProfile'),
        ),
    ]
