# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0013_pub_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticssingleton',
            name='pubsWithPrices',
            field=models.IntegerField(default=0),
        ),
    ]
