# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0014_statisticssingleton_pubswithprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='standardDevation',
            new_name='standardDeviation',
        ),
    ]
