# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0015_auto_20180131_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontributionssingleton',
            name='mostFirstVerified',
        ),
        migrations.RemoveField(
            model_name='usercontributionssingleton',
            name='mostLastVerified',
        ),
        migrations.RemoveField(
            model_name='usercontributionssingleton',
            name='mostVisited',
        ),
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='cheapestPubs',
        ),
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='dearestPubs',
        ),
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='pubsWithPrices',
        ),
        migrations.AddField(
            model_name='statisticssingleton',
            name='pubsWithPrices',
            field=models.ManyToManyField(to='Guindex.Pub'),
        ),
        migrations.DeleteModel(
            name='UserContributionsSingleton',
        ),
    ]
