# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 10:24
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0016_auto_20180201_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('53.185403')), django.core.validators.MaxValueValidator(Decimal('53.635552'))]),
        ),
        migrations.AlterField(
            model_name='pub',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-6.547498')), django.core.validators.MaxValueValidator(Decimal('-6.042723'))]),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=40, unique=False),
        ),
    ]
