# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0017_auto_20180206_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guinness',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='pendingApprovalTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='pendingClosedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='pendingNotServingGuinnessTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
