# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0018_auto_20180206_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='guinness',
            name='rejectReason',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
