# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 12:57
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0020_pub_pendingapprovalrejectreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='pendingClosedRejectReason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='pendingNotServingGuinnessRejectReason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='averagePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=4),
        ),
    ]
