# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0021_auto_20180212_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='pendingApprovalRejected',
            new_name='rejected',
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='rejectReason',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingApproval',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingApprovalContributor',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingApprovalRejectReason',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingApprovalTime',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingClosed',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingClosedContributor',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingClosedRejectReason',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingClosedTime',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingNotServingGuinness',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingNotServingGuinnessContributor',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingNotServingGuinnessRejectReason',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pendingNotServingGuinnessTime',
        ),
        migrations.AddField(
            model_name='guinness',
            name='clonedFrom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guindex.Guinness'),
        ),
        migrations.AddField(
            model_name='guinness',
            name='isPendingContribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pub',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='clonedFrom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AddField(
            model_name='pub',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='pub',
            name='isPendingContribution',
            field=models.BooleanField(default=False),
        ),
    ]
