# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 11:15
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180112_2059'),
        ('Guindex', '0023_auto_20180215_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubPendingCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-6.547498')), django.core.validators.MaxValueValidator(Decimal('-6.042723'))])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('53.185403')), django.core.validators.MaxValueValidator(Decimal('53.635552'))])),
                ('mapLink', models.TextField(default=b'')),
                ('closed', models.BooleanField(default=False)),
                ('servingGuinness', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PubPendingPatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-6.547498')), django.core.validators.MaxValueValidator(Decimal('-6.042723'))])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('53.185403')), django.core.validators.MaxValueValidator(Decimal('53.635552'))])),
                ('mapLink', models.TextField(default=b'')),
                ('closed', models.BooleanField(default=False)),
                ('servingGuinness', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='clonedFrom',
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='hasPendingContribution',
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='isPendingContribution',
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='rejectReason',
        ),
        migrations.RemoveField(
            model_name='guinness',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='clonedFrom',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='hasPendingContribution',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='isPendingContribution',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='rejectReason',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='rejected',
        ),
        migrations.AddField(
            model_name='pubpendingpatch',
            name='clonedFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AddField(
            model_name='pubpendingpatch',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile'),
        ),
    ]
