# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0025_guinnesspendingcreate_guinnesspendingpatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuindexUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubsVisited', models.IntegerField(default=0)),
                ('originalPrices', models.IntegerField(default=0)),
                ('currentVerifications', models.IntegerField(default=0)),
                ('lastCalculated', models.DateTimeField(auto_now=True)),
                ('userProfile', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guindexuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
