# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0027_auto_20180305_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='guindexuser',
            name='usingEmailAlerts',
            field=models.BooleanField(default=False),
        ),
    ]
