# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0028_guindexuser_usingemailalerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='county',
            field=models.CharField(choices=[(b'Cavan', b'Cavan'), (b'Carlow', b'Carlow'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', max_length=15),
        ),
        migrations.AddField(
            model_name='pubpendingcreate',
            name='county',
            field=models.CharField(choices=[(b'Cavan', b'Cavan'), (b'Carlow', b'Carlow'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', max_length=15),
        ),
        migrations.AddField(
            model_name='pubpendingpatch',
            name='county',
            field=models.CharField(choices=[(b'Cavan', b'Cavan'), (b'Carlow', b'Carlow'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', max_length=15),
        ),
        migrations.AlterField(
            model_name='pub',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='pub',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
    ]
