# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0030_auto_20180525_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
