# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0032_guindexuser_isdeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticssingleton',
            name='numUsers',
            field=models.IntegerField(default=0),
        ),
    ]
