# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0033_statisticssingleton_numusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='lastPrice',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='lastSubmissionTime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
