# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0035_auto_20180821_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guinnesspendingpatch',
            name='clonedFrom',
        ),
        migrations.RemoveField(
            model_name='guinnesspendingpatch',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='guinnesspendingpatch',
            name='pub',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='lastPrice',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='lastSubmissionTime',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='statisticssingleton',
            name='pubsWithPrices',
        ),
        migrations.DeleteModel(
            name='GuinnessPendingPatch',
        ),
    ]
