# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-20 16:05
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0036_auto_20180914_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='lastPrice',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='lastSubmissionTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='currentVerifications',
            field=models.IntegerField(default=0, help_text=b'Number of current verifactions for this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='isDeveloper',
            field=models.BooleanField(default=False, help_text=b'Is this contributor a developer of the Guindex website?'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='lastCalculated',
            field=models.DateTimeField(auto_now=True, help_text=b'UTC timestamp of when statistics were last calculated for this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='originalPrices',
            field=models.IntegerField(default=0, help_text=b'Number of first prices for a pub submitted by this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='pubsVisited',
            field=models.IntegerField(default=0, help_text=b'Number of pubs visited by this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='user',
            field=models.OneToOneField(blank=True, default=None, help_text=b'User ID associated with this contributor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guindexuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='usingEmailAlerts',
            field=models.BooleanField(default=False, help_text=b'Does this contributor have email alerts enabled?'),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'UTC timestamp of when price was submitted'),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text=b'ID of user who submitted this price', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text=b'Price', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='pub',
            field=models.ForeignKey(help_text=b'ID of pub this price belongs to', on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='starRating',
            field=models.IntegerField(default=None, help_text=b'Star rating (i.e. quality of pint)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'UTC timestamp of when price was submitted'),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text=b'ID of user who submitted this price', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text=b'Price', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='pub',
            field=models.ForeignKey(help_text=b'ID of pub this price belongs to', on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='starRating',
            field=models.IntegerField(default=None, help_text=b'Star rating (i.e. quality of pint)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pub',
            name='averageRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text=b'Average star rating of pints submitted for this pub', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AlterField(
            model_name='pub',
            name='closed',
            field=models.BooleanField(default=False, help_text=b'Is pub permanently closed?'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='county',
            field=models.CharField(choices=[(b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', help_text=b'County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pub',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'UTC timestamp of when pub was created'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text=b'ID of user who created this pub', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pub',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text=b'Latitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pub',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text=b'Longitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pub',
            name='mapLink',
            field=models.TextField(default=b'', help_text=b'Link to pub location in google maps'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(help_text=b'Pub name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pub',
            name='servingGuinness',
            field=models.BooleanField(default=True, help_text=b'Is pub serving Guinness?'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='closed',
            field=models.BooleanField(default=False, help_text=b'Is pub permanently closed?'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='county',
            field=models.CharField(choices=[(b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', help_text=b'County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'UTC timestamp of when pub was created'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text=b'ID of user who created this pub', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text=b'Latitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text=b'Longitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='mapLink',
            field=models.TextField(default=b'', help_text=b'Link to pub location in google maps'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='name',
            field=models.CharField(help_text=b'Pub name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='servingGuinness',
            field=models.BooleanField(default=True, help_text=b'Is pub serving Guinness?'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='clonedFrom',
            field=models.ForeignKey(help_text=b'Pub this patch was applied to', on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='closed',
            field=models.BooleanField(default=False, help_text=b'Is pub permanently closed?'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='county',
            field=models.CharField(choices=[(b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', help_text=b'County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'UTC timestamp of when pub was created'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text=b'ID of user who created this pub', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text=b'Latitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text=b'Longitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='mapLink',
            field=models.TextField(default=b'', help_text=b'Link to pub location in google maps'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='name',
            field=models.CharField(help_text=b'Pub name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='servingGuinness',
            field=models.BooleanField(default=True, help_text=b'Is pub serving Guinness?'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='averagePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text=b'Average price from all pubs with registered prices', max_digits=4),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='closedPubs',
            field=models.IntegerField(default=0, help_text=b'Number of pubs marked as closed'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='lastCalculated',
            field=models.DateTimeField(auto_now=True, help_text=b'UTC timestamp of when statistics were last calculated'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='notServingGuinness',
            field=models.IntegerField(default=0, help_text=b'Number of pubs marked as not serving Guinness'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='numUsers',
            field=models.IntegerField(default=0, help_text=b'Number of user accounts'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='percentageVisited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text=b'Percentage of pubs in database visited by one or more users', max_digits=5),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='pubsInDb',
            field=models.IntegerField(default=0, help_text=b'Number of pubs in database'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='standardDeviation',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), help_text=b'Standard deviation', max_digits=12),
        ),
    ]
