# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0037_auto_20180920_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertsSingleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastCheckTime', models.DateTimeField(auto_now=True, help_text=b'Last time alerts were checked')),
            ],
        ),
    ]
