# Generated by Django 2.2.28 on 2023-09-29 16:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0038_alertssingleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertssingleton',
            name='lastCheckTime',
            field=models.DateTimeField(auto_now=True, help_text='Last time alerts were checked'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='currentVerifications',
            field=models.IntegerField(default=0, help_text='Number of current verifactions for this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='isDeveloper',
            field=models.BooleanField(default=False, help_text='Is this contributor a developer of the Guindex website?'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='lastCalculated',
            field=models.DateTimeField(auto_now=True, help_text='UTC timestamp of when statistics were last calculated for this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='originalPrices',
            field=models.IntegerField(default=0, help_text='Number of first prices for a pub submitted by this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='pubsVisited',
            field=models.IntegerField(default=0, help_text='Number of pubs visited by this contributor'),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='user',
            field=models.OneToOneField(blank=True, default=None, help_text='User ID associated with this contributor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guindexuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guindexuser',
            name='usingEmailAlerts',
            field=models.BooleanField(default=False, help_text='Does this contributor have email alerts enabled?'),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp of when price was submitted'),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text='ID of user who submitted this price', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='pub',
            field=models.ForeignKey(help_text='ID of pub this price belongs to', on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AlterField(
            model_name='guinness',
            name='starRating',
            field=models.IntegerField(default=None, help_text='Star rating (i.e. quality of pint)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp of when price was submitted'),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text='ID of user who submitted this price', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='pub',
            field=models.ForeignKey(help_text='ID of pub this price belongs to', on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AlterField(
            model_name='guinnesspendingcreate',
            name='starRating',
            field=models.IntegerField(default=None, help_text='Star rating (i.e. quality of pint)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pub',
            name='averageRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Average star rating of pints submitted for this pub', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AlterField(
            model_name='pub',
            name='closed',
            field=models.BooleanField(default=False, help_text='Is pub permanently closed?'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='county',
            field=models.CharField(choices=[('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Donegal', 'Donegal'), ('Dublin', 'Dublin'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='Dublin', help_text='County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pub',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp of when pub was created'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text='ID of user who created this pub', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pub',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text='Latitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pub',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text='Longitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pub',
            name='mapLink',
            field=models.TextField(default='', help_text='Link to pub location in google maps'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(help_text='Pub name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pub',
            name='servingGuinness',
            field=models.BooleanField(default=True, help_text='Is pub serving Guinness?'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='closed',
            field=models.BooleanField(default=False, help_text='Is pub permanently closed?'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='county',
            field=models.CharField(choices=[('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Donegal', 'Donegal'), ('Dublin', 'Dublin'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='Dublin', help_text='County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp of when pub was created'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text='ID of user who created this pub', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text='Latitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text='Longitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='mapLink',
            field=models.TextField(default='', help_text='Link to pub location in google maps'),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='name',
            field=models.CharField(help_text='Pub name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='servingGuinness',
            field=models.BooleanField(default=True, help_text='Is pub serving Guinness?'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='clonedFrom',
            field=models.ForeignKey(help_text='Pub this patch was applied to', on_delete=django.db.models.deletion.CASCADE, to='Guindex.Pub'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='closed',
            field=models.BooleanField(default=False, help_text='Is pub permanently closed?'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='county',
            field=models.CharField(choices=[('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Donegal', 'Donegal'), ('Dublin', 'Dublin'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='Dublin', help_text='County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp of when pub was created'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, help_text='ID of user who created this pub', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text='Latitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text='Longitude of pub location', max_digits=23),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='mapLink',
            field=models.TextField(default='', help_text='Link to pub location in google maps'),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='name',
            field=models.CharField(help_text='Pub name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='servingGuinness',
            field=models.BooleanField(default=True, help_text='Is pub serving Guinness?'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='averagePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Average price from all pubs with registered prices', max_digits=4),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='closedPubs',
            field=models.IntegerField(default=0, help_text='Number of pubs marked as closed'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='lastCalculated',
            field=models.DateTimeField(auto_now=True, help_text='UTC timestamp of when statistics were last calculated'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='notServingGuinness',
            field=models.IntegerField(default=0, help_text='Number of pubs marked as not serving Guinness'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='numUsers',
            field=models.IntegerField(default=0, help_text='Number of user accounts'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='percentageVisited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Percentage of pubs in database visited by one or more users', max_digits=5),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='pubsInDb',
            field=models.IntegerField(default=0, help_text='Number of pubs in database'),
        ),
        migrations.AlterField(
            model_name='statisticssingleton',
            name='standardDeviation',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), help_text='Standard deviation', max_digits=12),
        ),
    ]
