# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2026-04-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0038_alertssingleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='county',
            field=models.CharField(choices=[(b'Antrim', b'Antrim'), (b'Armagh', b'Armagh'), (b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Derry', b'Derry'), (b'Donegal', b'Donegal'), (b'Down', b'Down'), (b'Dublin', b'Dublin'), (b'Fermanagh', b'Fermanagh'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Tyrone', b'Tyrone'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', help_text=b'County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pubpendingcreate',
            name='county',
            field=models.CharField(choices=[(b'Antrim', b'Antrim'), (b'Armagh', b'Armagh'), (b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Derry', b'Derry'), (b'Donegal', b'Donegal'), (b'Down', b'Down'), (b'Dublin', b'Dublin'), (b'Fermanagh', b'Fermanagh'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Tyrone', b'Tyrone'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', help_text=b'County pub is located in', max_length=15),
        ),
        migrations.AlterField(
            model_name='pubpendingpatch',
            name='county',
            field=models.CharField(choices=[(b'Antrim', b'Antrim'), (b'Armagh', b'Armagh'), (b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Derry', b'Derry'), (b'Donegal', b'Donegal'), (b'Down', b'Down'), (b'Dublin', b'Dublin'), (b'Fermanagh', b'Fermanagh'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Sligo', b'Sligo'), (b'Tipperary', b'Tipperary'), (b'Tyrone', b'Tyrone'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], default=b'Dublin', help_text=b'County pub is located in', max_length=15),
        ),
    ]
