# Generated by Django 2.2.28 on 2023-09-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0039_auto_20230929_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='pubpendingcreate',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='pubpendingpatch',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
