# Generated by Django 2.2.28 on 2023-09-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0040_auto_20230929_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='mapLink',
            new_name='map_link',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='servingGuinness',
            new_name='serving_guinness',
        ),
        migrations.RenameField(
            model_name='pubpendingcreate',
            old_name='mapLink',
            new_name='map_link',
        ),
        migrations.RenameField(
            model_name='pubpendingcreate',
            old_name='servingGuinness',
            new_name='serving_guinness',
        ),
        migrations.RenameField(
            model_name='pubpendingpatch',
            old_name='mapLink',
            new_name='map_link',
        ),
        migrations.RenameField(
            model_name='pubpendingpatch',
            old_name='servingGuinness',
            new_name='serving_guinness',
        ),
    ]
