# Generated by Django 2.2.28 on 2023-09-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0043_auto_20230929_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guinness',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='guinness',
            old_name='starRating',
            new_name='star_rating',
        ),
        migrations.RenameField(
            model_name='guinnesspendingcreate',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='guinnesspendingcreate',
            old_name='starRating',
            new_name='star_rating',
        ),
    ]
