# Generated by Django 2.2.28 on 2023-09-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0044_auto_20230929_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='averagePrice',
            new_name='average_price',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='closedPubs',
            new_name='closed_pubs',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='lastCalculated',
            new_name='last_calculated',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='notServingGuinness',
            new_name='not_serving_guinness',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='numUsers',
            new_name='num_users',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='percentageVisited',
            new_name='percentage_visited',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='pubsInDb',
            new_name='pubs_in_db',
        ),
        migrations.RenameField(
            model_name='statisticssingleton',
            old_name='standardDeviation',
            new_name='standard_deviation',
        ),
    ]
