# Generated by Django 2.2.28 on 2023-09-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0045_auto_20230929_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guindexuser',
            old_name='currentVerifications',
            new_name='current_verifications',
        ),
        migrations.RenameField(
            model_name='guindexuser',
            old_name='isDeveloper',
            new_name='is_developer',
        ),
        migrations.RenameField(
            model_name='guindexuser',
            old_name='lastCalculated',
            new_name='last_calculated',
        ),
        migrations.RenameField(
            model_name='guindexuser',
            old_name='originalPrices',
            new_name='original_prices',
        ),
        migrations.RenameField(
            model_name='guindexuser',
            old_name='pubsVisited',
            new_name='pubs_visited',
        ),
        migrations.RenameField(
            model_name='guindexuser',
            old_name='usingEmailAlerts',
            new_name='using_email_alerts',
        ),
    ]
