# Generated by Django 2.2.28 on 2023-09-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0046_auto_20230929_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertssingleton',
            old_name='lastCheckTime',
            new_name='last_check_time',
        ),
    ]
