"""
Django settings for GuindexProject project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from . import secrets

PROJECT_TITLE = "Guindex"

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets.KEY

# SECURITY WARNING: don't run with debug turned on in production!
# Local dev: export DJANGO_DEBUG=1  (registration API and extra checks)
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# Enable timezone support
USE_TZ = True

ALLOWED_HOSTS = ['45.79.148.4', 'guindex.ie', 'www.guindex.ie', '127.0.0.1', '172.28.5.22', '172.28.4.152']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_datatables',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'corsheaders',
    'UserProfile',
    'Guindex',
    'GuindexWebClient',
    'TelegramUser',
)

SITE_ID = 1 # Need for rest_auth stuff

# Django 2.0+: MIDDLEWARE (not MIDDLEWARE_CLASSES); SessionAuthenticationMiddleware removed
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
# Legacy name still read by some django-cors-headers versions:
CORS_ORIGIN_ALLOW_ALL = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow embedding /new_guindex_map in same-origin iframe (map tab)
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'GuindexProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GuindexProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# SQLite: GUINDEX_DATABASE_PATH overrides. Otherwise prefer repo-root Guindex.db (next to GuindexProject/),
# then GuindexProject/Guindex.db. Production often uses export GUINDEX_DATABASE_PATH=/usr/share/Guindex.db
_REPO_DIR = os.path.dirname(BASE_DIR)


def _sqlite_database_path():
    override = os.environ.get('GUINDEX_DATABASE_PATH', '').strip()
    if override:
        return override
    repo_db = os.path.join(_REPO_DIR, 'Guindex.db')
    local_db = os.path.join(BASE_DIR, 'Guindex.db')
    if os.path.isfile(repo_db):
        return repo_db
    return local_db


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _sqlite_database_path(),
    }
}

# Cache: DB cache needs `python manage.py createcachetable`. Default LocMem avoids that for local dev.
# Production with DB cache: export GUINDEX_USE_DB_CACHE=1 && createcachetable
if os.environ.get('GUINDEX_USE_DB_CACHE', '0') == '1':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'guindex_cache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'guindex',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "CDN/")

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = secrets.EMAIL
EMAIL_HOST_PASSWORD = secrets.PASSWORD
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

# Log files: os.path.join(BASE_DIR, "/var/log/...") ignores BASE_DIR (absolute second path → /var/log).
# Default: GuindexProject/logs/. Production: export GUINDEX_LOG_DIR=/var/log
LOG_ROOT = os.environ.get('GUINDEX_LOG_DIR', os.path.join(BASE_DIR, 'logs')).rstrip(os.sep)
if not os.path.isdir(LOG_ROOT):
    try:
        os.makedirs(LOG_ROOT)
    except OSError:
        pass

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'TelegramUserLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'TelegramUser.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'Guindex.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexWebClientLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'GuindexWebClient.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexStatsLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'GuindexStats.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexAlertsLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'GuindexAlerts.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexDbBackupLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'GuindexDbBackup.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexBotLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'GuindexBot.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
        'GuindexMapLogFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_ROOT, 'GuindexMap.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'TelegramUser': {
            'handlers': ['TelegramUserLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'Guindex': {
            'handlers': ['GuindexLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'GuindexWebClient': {
            'handlers': ['GuindexWebClientLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'GuindexStats': {
            'handlers': ['GuindexStatsLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'GuindexAlerts': {
            'handlers': ['GuindexAlertsLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'GuindexDbBackup': {
            'handlers': ['GuindexDbBackupLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'GuindexBot': {
            'handlers': ['GuindexBotLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
        'GuindexMap': {
            'handlers': ['GuindexMapLogFile'],
            'propogate': True,
            'level': 'DEBUG',
        },
    }
}

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',     
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_datatables.filters.DatatablesFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10000/day',
        'user': '10000/day'
    }
}

# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Telegram API
BOT_HTTP_API_TOKEN = secrets.BOT_HTTP_API_TOKEN

# Google Maps API
GOOGLE_MAPS_API_KEY = secrets.GOOGLE_MAPS_API_KEY

# Dropbox API
DROPBOX_API_KEY          = secrets.DROPBOX_API_KEY
DROPBOX_API_SECRET       = secrets.DROPBOX_API_SECRET
DROPBOX_API_ACCESS_TOKEN = secrets.DROPBOX_API_ACCESS_TOKEN

# Facebook Login API
FACEBOOK_APP_ID = secrets.FACEBOOK_APP_ID

# Google Analytics API
GOOGLE_ANALYTICS_KEY = secrets.GOOGLE_ANALYTICS_KEY

# django-allauth 65+ (replaces ACCOUNT_AUTHENTICATION_METHOD / *_EMAIL_REQUIRED / *_USERNAME_REQUIRED)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

AUTHENTICATION_BACKENDS = (
 # Needed to login by username in Django admin, regardless of `allauth`
 "django.contrib.auth.backends.ModelBackend",

 # `allauth` specific authentication methods, such as login by e-mail
 "allauth.account.auth_backends.AuthenticationBackend",
)

# dj-rest-auth reads REST_AUTH (not REST_AUTH_SERIALIZERS) for TOKEN_SERIALIZER, etc.
REST_AUTH = {
    'TOKEN_SERIALIZER': 'UserProfile.serializers.TokenSerializer',
}
