# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0002_auto_20171226_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuindexUser',
            fields=[
                ('userprofileplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserProfile.UserProfilePlugin')),
                ('pubsVisited', models.IntegerField(default=True)),
                ('originalPrices', models.IntegerField(default=True)),
                ('currentVerifications', models.IntegerField(default=True)),
            ],
            bases=('UserProfile.userprofileplugin',),
        ),
    ]
