# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180112_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegramuser',
        ),
    ]
