# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20180220_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfilePlugin',
        ),
    ]
