# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_facebookuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usingEmailAlerts',
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='facebookId',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accountActivationKey',
            field=models.CharField(max_length=12, unique=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passwordResetToken',
            field=models.CharField(max_length=12, unique=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passwordResetTokenExpiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
