# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guindex', '0027_auto_20180305_1738'),
        ('TelegramUser', '0004_auto_20180305_1738'),
        ('UserProfile', '0006_auto_20180305_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FacebookUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
